version: '3.8'

services:
  # PostgreSQL Database
  postgresql:
    image: postgres:16-alpine
    container_name: better-starlite-postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tests/sql/postgresql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: better-starlite-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./tests/sql/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpass"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

  # Oracle Database (XE - Express Edition)
  # Note: Oracle XE is large (~2GB) and slower to start
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: better-starlite-oracle
    environment:
      ORACLE_PASSWORD: OraclePass123
      APP_USER: testuser
      APP_USER_PASSWORD: testpass
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./tests/sql/oracle:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "sqlplus -L testuser/testpass@//localhost:1521/XEPDB1 @/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10
    # Oracle XE takes longer to start
    shm_size: 1gb

  # Microsoft SQL Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: better-starlite-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MssqlPass123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./tests/sql/mssql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P MssqlPass123! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mysql_data:
  oracle_data:
  mssql_data:

networks:
  default:
    name: better-starlite-network
